apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: infer-app-hpa
  namespace: infer-app-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infer-app-dp

  minReplicas: 3
  maxReplicas: 5

  metrics:
    - type: Pods
      pods:
        metric:
          name: inference_processing_seconds
        target:
          type: AverageValue
          averageValue: 500m
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
        - type: Percent
          value: 100
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300