apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-dp
  namespace: ml-inference-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      containers:
        - name: ml-inference-cn
          image: ml-inference-img
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
            - containerPort: 9000