apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ml-inference-scaler
  namespace: ml-inference-ns
spec:
  scaleTargetRef:
    name: ml-inference-dp

  minReplicaCount: 3
  maxReplicaCount: 10

  pollingInterval: 5
  cooldownPeriod: 30

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 90


  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.ml-inference-ns.svc.cluster.local:9090
        metricName: dispatcher_p95_latency
        query: |
          histogram_quantile(
            0.95,
            sum(rate(inference_request_latency_seconds_bucket[30s])) by (le)
          )
        threshold: "0.4"
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.ml-inference-ns.svc.cluster.local:9090
        metricName: dispatcher_pending_requests
        query: sum(dispatcher_pending_requests)
        threshold: "3"