apiVersion: v1
kind: Service
metadata:
  name: infer-app-svc
  namespace: infer-app-ns
  labels:
    app: infer-app
spec:
  selector:
    app: infer-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  type: NodePort